#!/bin/bash
# Autogenerated deploy script for backend

echo "Starting deployment..."

# Pull the latest changes from the main branch
git pull origin main

# If you use a virtual environment, activate it and install dependencies:
if [ -d ".venv" ]; then
    source .venv/bin/activate
    pip install -r requirements.txt
fi

# Apply any new database migrations
# python run_migration.py # Uncomment if you have auto-migrations

# Restart the backend service
# ⚠️ IMPORTANT: Uncomment the correct line for your server setup! ⚠️

# If using systemctl (recommended for VPS):
# sudo systemctl restart backend
# sudo systemctl restart tattoo-backend
# sudo systemctl restart uvicorn

# If using pm2:
# pm2 restart backend

# If using docker-compose:
# docker-compose up -d --build

echo "Deployment finished!"
